# Generated by Django 5.1.4 on 2024-12-05 10:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("vacancy", "0002_alter_company_options"),
    ]

    operations = [
        migrations.AlterField(
            model_name="job",
            name="max_salary",
            field=models.DecimalField(
                decimal_places=2, max_digits=10, verbose_name="Maximum Salary USD"
            ),
        ),
        migrations.AlterField(
            model_name="job",
            name="min_salary",
            field=models.DecimalField(
                decimal_places=2, max_digits=10, verbose_name="Minimum Salary USD"
            ),
        ),
    ]
