# Generated by Django 5.1.4 on 2024-12-05 10:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("vacancy", "0003_alter_job_max_salary_alter_job_min_salary"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="job",
            name="salary_distribution_period",
        ),
        migrations.AlterField(
            model_name="job",
            name="max_salary",
            field=models.DecimalField(
                decimal_places=2,
                max_digits=10,
                verbose_name="Maximum Annual Salary USD",
            ),
        ),
        migrations.AlterField(
            model_name="job",
            name="min_salary",
            field=models.DecimalField(
                decimal_places=2,
                max_digits=10,
                verbose_name="Minimum Annual Salary USD",
            ),
        ),
    ]
