# Generated by Django 5.1.4 on 2024-12-09 09:24

import versatileimagefield.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("vacancy", "0007_industry_jobcategory_job_category"),
    ]

    operations = [
        migrations.AddField(
            model_name="job",
            name="image",
            field=versatileimagefield.fields.VersatileImageField(
                blank=True, null=True, upload_to="images/jobs/"
            ),
        ),
    ]
