# Generated by Django 5.1.4 on 2024-12-09 09:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("vacancy", "0008_job_image"),
    ]

    operations = [
        migrations.AddField(
            model_name="job",
            name="currency",
            field=models.CharField(default="USD", max_length=255),
        ),
    ]
