# Generated by Django 5.1.4 on 2024-12-09 09:50

import versatileimagefield.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("vacancy", "0009_job_currency"),
    ]

    operations = [
        migrations.AlterField(
            model_name="company",
            name="logo",
            field=versatileimagefield.fields.VersatileImageField(
                blank=True, null=True, upload_to="images/company_logos/"
            ),
        ),
    ]
