# Generated by Django 5.1.4 on 2024-12-05 08:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("config", "0001_initial"),
    ]

    operations = [
        migrations.DeleteModel(
            name="SiteConfig",
        ),
    ]
