# Generated by Django 5.1.4 on 2024-12-05 08:09

import versatileimagefield.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("config", "0002_delete_siteconfig"),
    ]

    operations = [
        migrations.CreateModel(
            name="SiteConfig",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("site_title", models.CharField(max_length=255)),
                (
                    "logo",
                    versatileimagefield.fields.VersatileImageField(
                        blank=True, null=True, upload_to="images/logo/"
                    ),
                ),
                ("address", models.CharField(blank=True, max_length=255, null=True)),
                ("phone", models.CharField(blank=True, max_length=255, null=True)),
                ("email", models.EmailField(blank=True, max_length=254, null=True)),
                ("social_links", models.ManyToManyField(blank=True, to="config.link")),
            ],
            options={
                "abstract": False,
            },
        ),
    ]
