# Generated by Django 5.1.4 on 2024-12-05 08:22

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("config", "0003_siteconfig"),
    ]

    operations = [
        migrations.CreateModel(
            name="Address",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("address", models.CharField(max_length=255)),
            ],
        ),
        migrations.RemoveField(
            model_name="siteconfig",
            name="address",
        ),
        migrations.RemoveField(
            model_name="siteconfig",
            name="phone",
        ),
        migrations.AddField(
            model_name="siteconfig",
            name="phone_numbers",
            field=django.contrib.postgres.fields.ArrayField(
                base_field=models.CharField(max_length=255),
                blank=True,
                null=True,
                size=None,
            ),
        ),
        migrations.AlterField(
            model_name="siteconfig",
            name="email",
            field=django.contrib.postgres.fields.ArrayField(
                base_field=models.EmailField(max_length=254),
                blank=True,
                null=True,
                size=None,
            ),
        ),
        migrations.AddField(
            model_name="siteconfig",
            name="addresses",
            field=models.ManyToManyField(blank=True, to="config.address"),
        ),
    ]
