# Generated by Django 5.1.4 on 2024-12-05 08:36

import django.contrib.postgres.fields
import versatileimagefield.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("config", "0005_rename_email_siteconfig_emails"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="siteconfig",
            name="addresses",
        ),
        migrations.AlterModelOptions(
            name="siteconfig",
            options={
                "verbose_name": "Configuration",
                "verbose_name_plural": "Configuration",
            },
        ),
        migrations.AddField(
            model_name="siteconfig",
            name="address",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name="siteconfig",
            name="emails",
            field=django.contrib.postgres.fields.ArrayField(
                base_field=models.EmailField(max_length=254),
                blank=True,
                help_text="Enter emails separated by comma.",
                null=True,
                size=None,
            ),
        ),
        migrations.AlterField(
            model_name="siteconfig",
            name="logo",
            field=versatileimagefield.fields.VersatileImageField(
                blank=True,
                null=True,
                upload_to="images/logo/",
                verbose_name="Company Logo",
            ),
        ),
        migrations.AlterField(
            model_name="siteconfig",
            name="phone_numbers",
            field=django.contrib.postgres.fields.ArrayField(
                base_field=models.CharField(max_length=255),
                blank=True,
                help_text="Enter phone numbers separatedd by comma.",
                null=True,
                size=None,
            ),
        ),
        migrations.AlterField(
            model_name="siteconfig",
            name="site_title",
            field=models.CharField(max_length=255, verbose_name="Company Name"),
        ),
        migrations.DeleteModel(
            name="Address",
        ),
    ]
