# Generated by Django 5.1.4 on 2024-12-05 08:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("config", "0008_alter_siteconfig_options_person_image"),
    ]

    operations = [
        migrations.AddField(
            model_name="siteconfig",
            name="company_registrar_number",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name="siteconfig",
            name="government_license_number",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name="siteconfig",
            name="website",
            field=models.URLField(blank=True, max_length=255, null=True),
        ),
    ]
