# Generated by Django 5.1.4 on 2024-12-05 08:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("config", "0009_siteconfig_company_registrar_number_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="siteconfig",
            name="pan",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
