# Generated by Django 5.1.4 on 2024-12-05 09:09

import django_ckeditor_5.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("config", "0011_alter_siteconfig_pan"),
    ]

    operations = [
        migrations.AddField(
            model_name="person",
            name="message",
            field=django_ckeditor_5.fields.CKEditor5Field(blank=True, null=True),
        ),
    ]
