# Generated by Django 5.1.4 on 2024-12-05 09:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("config", "0012_person_message"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="person",
            name="config",
        ),
    ]
