# Generated by Django 5.1.4 on 2024-12-05 09:25

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("config", "0013_remove_person_config"),
    ]

    operations = [
        migrations.AddField(
            model_name="siteconfig",
            name="paid_up_capital",
            field=models.PositiveBigIntegerField(
                blank=True, null=True, verbose_name="Paid Up Capital in Nepali Rupees"
            ),
        ),
        migrations.AddField(
            model_name="siteconfig",
            name="working_countries",
            field=django.contrib.postgres.fields.ArrayField(
                base_field=models.CharField(max_length=255),
                blank=True,
                null=True,
                size=None,
            ),
        ),
    ]
