# Generated by Django 5.1.4 on 2024-12-05 10:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("config", "0015_siteconfig_mission_siteconfig_vision"),
    ]

    operations = [
        migrations.AddField(
            model_name="siteconfig",
            name="google_maps_link",
            field=models.URLField(blank=True, max_length=1024, null=True),
        ),
        migrations.AlterField(
            model_name="siteconfig",
            name="website",
            field=models.URLField(blank=True, max_length=1024, null=True),
        ),
    ]
