# Generated by Django 5.1.4 on 2024-12-06 07:09

import versatileimagefield.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("config", "0016_siteconfig_google_maps_link_alter_siteconfig_website"),
    ]

    operations = [
        migrations.CreateModel(
            name="Client",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=255)),
                (
                    "logo",
                    versatileimagefield.fields.VersatileImageField(
                        blank=True, null=True, upload_to="images/clients/"
                    ),
                ),
            ],
        ),
    ]
