# Generated by Django 5.1.4 on 2024-12-06 07:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("config", "0018_contactus_faq"),
    ]

    operations = [
        migrations.CreateModel(
            name="Document",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("title", models.CharField(max_length=255)),
                ("file", models.FileField(upload_to="files/documents/")),
            ],
            options={
                "abstract": False,
            },
        ),
    ]
