# Generated by Django 5.1.4 on 2024-12-06 10:37

import django_ckeditor_5.fields
import versatileimagefield.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Post",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("title", models.CharField(max_length=255)),
                ("slug", models.SlugField(max_length=255, unique=True)),
                (
                    "cover_image",
                    versatileimagefield.fields.VersatileImageField(
                        blank=True, null=True, upload_to="images/blog"
                    ),
                ),
                ("content", django_ckeditor_5.fields.CKEditor5Field()),
            ],
            options={
                "abstract": False,
            },
        ),
    ]
