# Generated by Django 5.1.4 on 2024-12-05 06:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="user",
            name="address_city",
        ),
        migrations.RemoveField(
            model_name="user",
            name="address_country",
        ),
        migrations.RemoveField(
            model_name="user",
            name="address_state",
        ),
        migrations.RemoveField(
            model_name="user",
            name="address_street1",
        ),
        migrations.RemoveField(
            model_name="user",
            name="address_street2",
        ),
        migrations.RemoveField(
            model_name="user",
            name="bio",
        ),
        migrations.RemoveField(
            model_name="user",
            name="date_of_birth",
        ),
        migrations.RemoveField(
            model_name="user",
            name="first_name",
        ),
        migrations.RemoveField(
            model_name="user",
            name="full_name",
        ),
        migrations.RemoveField(
            model_name="user",
            name="gender",
        ),
        migrations.RemoveField(
            model_name="user",
            name="last_name",
        ),
        migrations.RemoveField(
            model_name="user",
            name="middle_name",
        ),
        migrations.RemoveField(
            model_name="user",
            name="occupation",
        ),
        migrations.RemoveField(
            model_name="user",
            name="phone_number",
        ),
        migrations.RemoveField(
            model_name="user",
            name="profile_picture",
        ),
    ]
